import './src/js/components/headerSearch'
import './src/js/components/fonts'
import './src/js/components/floatingNav'
import './src/js/components/sliders'
import './src/js/components/imageFlipper'
import './src/js/components/quantity'
import './src/js/components/messengers'
import './src/js/components/formValidations'

import 'normalize.css'
import './src/scss/styles.scss'
